apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service-html
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events { worker_connections 1024; }
    http {
        include /etc/nginx/mime.types;
        server {
            listen 8080; # Port non-privilégié recommandé
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
        }
    }
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align: center; margin-top: 50px;">
        <h1>Hello, Knative!</h1>
        <h2>Mon IP de Pod est : <span style="color: blue;">xxx</span></h2>
      </body>
    </html>
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service-optimise
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - name: nginx
          image: nginx:alpine # Version alpine plus légère
          ports:
            - containerPort: 8080 # Doit correspondre au listen de nginx.conf
          volumeMounts:
            - name: nginx-conf
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html-writable
              mountPath: /usr/share/nginx/html # Chemin standard Nginx
      volumes:
        - name: nginx-conf
          configMap:
            name: config-service-html
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: config-source
          configMap:
            name: config-service-html
            items:
              - key: index.html
                path: index.html
        - name: nginx-html-writable
          emptyDir: {}
