apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["/bin/bash"]
      args: ["-c", "while true; do ping localhost; sleep 60;done"]
      ports:
        - name: http
          containerPort: 80
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
